"""데모용 임의 EditRecipe — READ-2 구조화 출력이라고 가정."""
from sarils_edit_engine.contracts import (EditRecipe, EffectApplication,
                                          FinalAudioPolicy, FontWeight, MotionId,
                                          Overlay, OverlayType, RecipeSegment,
                                          SfxStrength)


def build_recipe_a(duration_ms: int) -> EditRecipe:
    return EditRecipe(
        recipe_id="recipe_demo_apt_001",
        produced_video_id="prod_one_take_001",
        final_audio_policy=FinalAudioPolicy.SFX_ONLY,
        audio_mix_policy_id="SFX_ONLY_V1",
        segments=[
            RecipeSegment(recipe_segment_id="rs_001", produced_segment_id="ps_intro",
                          sequence_index=1, trim_in_ms=300, trim_out_ms=4200,
                          actual_video_evidence="0.3~4.2s 도입 포즈, 시작부 대기 300ms 제거"),
            RecipeSegment(recipe_segment_id="rs_002", produced_segment_id="ps_dance",
                          sequence_index=2, trim_in_ms=4200, trim_out_ms=12400,
                          actual_video_evidence="4.2~12.4s APT 손동작 구간"),
            RecipeSegment(recipe_segment_id="rs_003", produced_segment_id="ps_finale",
                          sequence_index=3, trim_in_ms=12400,
                          trim_out_ms=min(18100, duration_ms),
                          effects=[EffectApplication(effect_id="PUNCH_ZOOM",
                                                     params={"scale_end": 1.08})],
                          actual_video_evidence="12.4s~ 마무리 윙크 — punch zoom 강조"),
        ],
        overlays=[
            Overlay(overlay_id="ov_c1", produced_segment_id="ps_intro",
                    overlay_type=OverlayType.CAPTION, text_content="아파트 아파트",
                    style_id="CAPTION", start_ms=600, end_ms=3800,
                    motion_id=MotionId.POP, font_weight=FontWeight.SEMIBOLD),
            Overlay(overlay_id="ov_c2", produced_segment_id="ps_dance",
                    overlay_type=OverlayType.CAPTION,
                    text_content="이 챌린지 아직 안 해봤다면",
                    style_id="CAPTION", start_ms=4600, end_ms=7600,
                    motion_id=MotionId.FADE, font_weight=FontWeight.SEMIBOLD),
            Overlay(overlay_id="ov_t1", produced_segment_id="ps_dance",
                    overlay_type=OverlayType.TEXT_2D, text_content="APT. CHALLENGE",
                    style_id="TEXT_2D", start_ms=8300, end_ms=12000,
                    motion_id=MotionId.POP, font_weight=FontWeight.BOLD),
            Overlay(overlay_id="ov_cta", produced_segment_id="ps_finale",
                    overlay_type=OverlayType.CAPTION, text_content="저장하고 같이 춰봐요",
                    style_id="CTA_BOX", start_ms=15300, end_ms=17900,
                    motion_id=MotionId.FADE, font_weight=FontWeight.BOLD),
            Overlay(overlay_id="ov_sfx1", produced_segment_id="ps_dance",
                    overlay_type=OverlayType.SFX, sfx_intent_id="TEXT_POP",
                    start_ms=4600, end_ms=4800, audio_volume_db=-14,
                    sfx_strength=SfxStrength.LIGHT),
            Overlay(overlay_id="ov_sfx2", produced_segment_id="ps_dance",
                    overlay_type=OverlayType.SFX, sfx_intent_id="TEXT_POP",
                    start_ms=8300, end_ms=8500, audio_volume_db=-14,
                    sfx_strength=SfxStrength.LIGHT),
            Overlay(overlay_id="ov_sfx3", produced_segment_id="ps_finale",
                    overlay_type=OverlayType.SFX, sfx_intent_id="CTA_APPEAR",
                    start_ms=15300, end_ms=15650, audio_volume_db=-12,
                    sfx_strength=SfxStrength.MEDIUM),
        ],
    )
