from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import JSON, DateTime, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base


class EditingTemplate(Base):
    __tablename__ = "editing_templates"

    template_id: Mapped[str] = mapped_column(String(160), primary_key=True)
    version: Mapped[int] = mapped_column(Integer, primary_key=True)
    status: Mapped[str] = mapped_column(String(24), default="DRAFT", index=True)

    name: Mapped[str] = mapped_column(String(255))
    recommendation_title: Mapped[str] = mapped_column(String(255), default="")
    recommendation_concept: Mapped[str] = mapped_column(Text, default="")

    # Machine-readable constraints and recommendation hints. Hard constraints are
    # enforced in code before the LLM sees the candidate pool.
    recommendation_metadata: Mapped[dict] = mapped_column(JSON, default=dict)

    # Returned directly after recommendation acceptance; it is not regenerated by
    # the Shortform Agent.
    shooting_guide: Mapped[dict] = mapped_column(JSON, default=dict)

    # Reserved for the Editing Agent. The Shortform Agent only sees a summary.
    editing_rules: Mapped[dict] = mapped_column(JSON, default=dict)
    trend_ids: Mapped[list] = mapped_column(JSON, default=list)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )
